spring.application.name=cinema-events
server.port=${PORT}

#proxy.movies_migration_percent=${MOVIES_MIGRATION_PERCENT}
#proxy.movies_service_url=${MOVIES_SERVICE_URL}
#proxy.monolith_url=${MONOLITH_URL}

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.producer.properties.json.add.type.headers=true
spring.kafka.producer.properties.type.mappings=user_event:dev.bzd9.event.model.UserEvent,movie_event:dev.bzd9.event.model.MovieEvent,payment_event:dev.bzd9.event.model.PaymentEvent


# Consumer Configuration
spring.kafka.consumer.group-id=cinema-event-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.value.default.type=dev.bzd9.event.model.UserEvent
spring.kafka.consumer.properties.type.mappings=user_event:dev.bzd9.event.model.UserEvent,movie_event:dev.bzd9.event.model.MovieEvent,payment_event:dev.bzd9.event.model.PaymentEvent


# Topic Name
app.kafka.topic=cinema-event-topic
