apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZbVY2WkdWc2JtbHhkV1U2WjJod1h6Y3dXbUkwUzAxSlVqZExNV3RVTTFGTlEySXlhemsyY214R09HcFpVeko0U1hOTFJ3PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
